# HM1 - Serie 10

## Aufgabe 1 - Jacobi-Verfahren

In [4]:
import numpy as np
def jacobi(A,b,iter,x_start=None, p=False):
    x = x_start
    if x_start is None:
        x = np.zeros(len(A[0]))
    D = np.diag(A)
    D_inv= np.diag(1/A)
    L = np.tril(A, k=-1)
    R = np.triu(A, k=1)

    if p:
        print("L",L)
        print("R",R)
        print("D",D)
        print("D_inv",D_inv)
    for i in range(iter):
        x = -D_inv * ((L+R) @ x - b)
    return x

## Aufgabe 1a Konvergenz bzgl. Jacobi Verfahren

In [5]:
A = np.array([[8,5,2],[5,9,1],[4,2,7]])
b = np.array([19,5,34])
n = 1000

res1 = jacobi(A,b,n)
print("Aufgabe 1a mit n=" + str(n))
print(res1)

Aufgabe 1a mit n=1000
[ 2. -1.  4.]


## Aufgabe 1b Berechnung mit gegebenem x_0, n

In [6]:
x_b = np.array([1,-1,3])
n = 3
res2 = jacobi(A,b,n,x_b,p=True)
print("Aufgabe 1b mit n=" + str(n))
print(res2)

L [[0 0 0]
 [5 0 0]
 [4 2 0]]
R [[0 5 2]
 [0 0 1]
 [0 0 0]]
D [8 9 7]
D_inv [0.125      0.11111111 0.14285714]
Aufgabe 1b mit n=3
[ 2.20982143 -0.6521164   4.37755102]


## Aufgabe 1c a-posteriori Abschätzung / Absoluter Fehler

In [7]:
print("Absoluter Fehler", res2 - res1)

Absoluter Fehler [0.20982143 0.3478836  0.37755102]


## Aufgabe 1d a-priori Abschätzung von n für gegebenen max Fehler

In [8]:
max_fehler = 1e-4
res_exakt = np.array([2,-1,4])

for i in range(1000):
    if (jacobi(A,b,i) - res_exakt <= 1e-4).all():
        res4 = i
        break;

print("Absoluter Fehler <=" + str(max_fehler) + " ab i=" + str(res4))

Absoluter Fehler <=0.0001 ab i=2


## Aufgabe 1e a-priori Abschätzung von n für gegebenen max Fehler

In [9]:
x_b = np.array([1,-1,3])
x_start = jacobi(A,b,2,x_b)

for i_2 in range(1000):
    if (jacobi(A,b,i_2, x_start) - res_exakt <= 1e-4).all():
        res5 = i
        break;

print("Absoluter Fehler <=" + str(max_fehler) + " ab i=" + str(res5))

Absoluter Fehler <=0.0001 ab i=2


## Aufgabe 2: Gauss-Seidel

In [10]:
def gauss_seidel(A,b,iter,x_start=None):
    x = x_start
    if x_start is None:
            x = np.zeros(len(A[0]))
    n = len(A)
    for k in range(iter):
        for j in range(0, n):
            D_2 = b[j]
            for i in range(0, n):
                if(j != i):
                    D_2 -= A[j][i] * x[i]
            x[j] = D_2 / A[j][j]
    return x


## Aufgabe 2a Konvergenz bzgl. Gauss-Seidel Verfahren

In [11]:
A = np.array([[8,5,2],[5,9,1],[4,2,7]])
b = np.array([19,5,34])
iter = 3
res6 = gauss_seidel(A,b,iter)
print("Aufgabe 2a")
print(res6)

Aufgabe 2a
[ 1.94792995 -0.97361534  4.02221584]


## Aufgabe 2b Berechnung mit gegebenem x_0, n

In [12]:
x_b = np.array([1,-1,3])
iter = 1000
res7 = gauss_seidel(A,b,iter, x_b)
print("Aufgabe 1b mit n=" + str(n))
print(res7)

Aufgabe 1b mit n=3
[1 0 4]


## Aufgabe 2c a-posteriori Abschätzung / Absoluter Fehler

In [13]:
print("Absoluter Fehler", res7 - res6)

Absoluter Fehler [-0.94792995  0.97361534 -0.02221584]


## Aufgabe 2d a-priori Abschätzung von n für gegebenen max Fehler

In [14]:
max_fehler_2 = 1e-4
res_exakt_2 = np.array([2,-1,4])

for i in range(1000):
    if np.all(gauss_seidel(A,b,i) - res_exakt_2 <= max_fehler_2):
        res8 = i
        break;

print("Absoluter Fehler <=" + str(max_fehler_2) + " ab i=" + str(res8))

Absoluter Fehler <=0.0001 ab i=9


## Aufgabe 2e a-priori Abschätzung von n für gegebenen max Fehler

In [16]:
x_b_2 = np.array([1,-1,3])
x_start_2 = jacobi(A,b,2,x_b)

for i_2 in range(1000):
    if np.all(gauss_seidel(A,b,i_2,x_start_2) - res_exakt_2 <= max_fehler_2):
        res9 = i
        break;

print("Absoluter Fehler <=" + str(max_fehler_2) + " ab i=" + str(res9))

Absoluter Fehler <=0.0001 ab i=9
